name: Pull from DO Droplet

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install resources
        run: |-
          sudo apt-get install ssh
      - name: Fetch/reset
        env:
          DROPLET_KEY: ${{ secrets.DROPLET_KEY }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: |-
          key=$(mktemp)
          echo -n "$DROPLET_KEY" > "$key"
          ssh -o StrictHostKeyChecking=no -i "$key" "root@$DROPLET_IP" <<"EOF"
            cd /root/MooseBot
            systemctl stop moose

            count=1
            while :; do
              git fetch origin
              if [ $? -eq 0 ]; then
                git reset --hard origin/master
                break
              fi
              echo "Fetch failed, retrying... ($count)"
              let count=$count+1
              sleep 10
            done

            systemctl enable --now moose
          EOF

          rm -f "$key"
